// Mocks generated by Mockito 5.4.2 from annotations
// in ditonton/test/presentation/pages/detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i17;
import 'dart:ui' as _i20;

import 'package:dartz/dartz.dart' as _i18;
import 'package:ditonton/common/failure.dart' as _i19;
import 'package:ditonton/common/state_enum.dart' as _i15;
import 'package:ditonton/domain/entities/movie.dart' as _i16;
import 'package:ditonton/domain/entities/movie_detail.dart' as _i7;
import 'package:ditonton/domain/entities/tv_series.dart' as _i22;
import 'package:ditonton/domain/entities/tv_series_detail.dart' as _i13;
import 'package:ditonton/domain/usecases/get_movie_detail.dart' as _i2;
import 'package:ditonton/domain/usecases/get_movie_recommendations.dart' as _i3;
import 'package:ditonton/domain/usecases/get_tv_series_detail.dart' as _i8;
import 'package:ditonton/domain/usecases/get_tv_series_recommendations.dart'
    as _i9;
import 'package:ditonton/domain/usecases/get_watchlist_movie_status.dart'
    as _i4;
import 'package:ditonton/domain/usecases/get_watchlist_tv_series_status.dart'
    as _i10;
import 'package:ditonton/domain/usecases/remove_watchlist_movie.dart' as _i6;
import 'package:ditonton/domain/usecases/remove_watchlist_tv_series.dart'
    as _i12;
import 'package:ditonton/domain/usecases/save_watchlist_movie.dart' as _i5;
import 'package:ditonton/domain/usecases/save_watchlist_tv_series.dart' as _i11;
import 'package:ditonton/presentation/provider/movie_detail_notifier.dart'
    as _i14;
import 'package:ditonton/presentation/provider/tv_series_detail_notifier.dart'
    as _i21;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetMovieDetail_0 extends _i1.SmartFake
    implements _i2.GetMovieDetail {
  _FakeGetMovieDetail_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetMovieRecommendations_1 extends _i1.SmartFake
    implements _i3.GetMovieRecommendations {
  _FakeGetMovieRecommendations_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchListMovieStatus_2 extends _i1.SmartFake
    implements _i4.GetWatchListMovieStatus {
  _FakeGetWatchListMovieStatus_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveWatchlistMovie_3 extends _i1.SmartFake
    implements _i5.SaveWatchlistMovie {
  _FakeSaveWatchlistMovie_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveWatchlistMovie_4 extends _i1.SmartFake
    implements _i6.RemoveWatchlistMovie {
  _FakeRemoveWatchlistMovie_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieDetail_5 extends _i1.SmartFake implements _i7.MovieDetail {
  _FakeMovieDetail_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvSeriesDetail_6 extends _i1.SmartFake
    implements _i8.GetTvSeriesDetail {
  _FakeGetTvSeriesDetail_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvSeriesRecommendations_7 extends _i1.SmartFake
    implements _i9.GetTvSeriesRecommendations {
  _FakeGetTvSeriesRecommendations_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchListTvSeriesStatus_8 extends _i1.SmartFake
    implements _i10.GetWatchListTvSeriesStatus {
  _FakeGetWatchListTvSeriesStatus_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveWatchlistTvSeries_9 extends _i1.SmartFake
    implements _i11.SaveWatchlistTvSeries {
  _FakeSaveWatchlistTvSeries_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveWatchlistTvSeries_10 extends _i1.SmartFake
    implements _i12.RemoveWatchlistTvSeries {
  _FakeRemoveWatchlistTvSeries_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesDetail_11 extends _i1.SmartFake
    implements _i13.TvSeriesDetail {
  _FakeTvSeriesDetail_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovieDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailNotifier extends _i1.Mock
    implements _i14.MovieDetailNotifier {
  MockMovieDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetMovieDetail get getMovieDetail => (super.noSuchMethod(
        Invocation.getter(#getMovieDetail),
        returnValue: _FakeGetMovieDetail_0(
          this,
          Invocation.getter(#getMovieDetail),
        ),
      ) as _i2.GetMovieDetail);
  @override
  _i3.GetMovieRecommendations get getMovieRecommendations =>
      (super.noSuchMethod(
        Invocation.getter(#getMovieRecommendations),
        returnValue: _FakeGetMovieRecommendations_1(
          this,
          Invocation.getter(#getMovieRecommendations),
        ),
      ) as _i3.GetMovieRecommendations);
  @override
  _i4.GetWatchListMovieStatus get getWatchListStatus => (super.noSuchMethod(
        Invocation.getter(#getWatchListStatus),
        returnValue: _FakeGetWatchListMovieStatus_2(
          this,
          Invocation.getter(#getWatchListStatus),
        ),
      ) as _i4.GetWatchListMovieStatus);
  @override
  _i5.SaveWatchlistMovie get saveWatchlist => (super.noSuchMethod(
        Invocation.getter(#saveWatchlist),
        returnValue: _FakeSaveWatchlistMovie_3(
          this,
          Invocation.getter(#saveWatchlist),
        ),
      ) as _i5.SaveWatchlistMovie);
  @override
  _i6.RemoveWatchlistMovie get removeWatchlist => (super.noSuchMethod(
        Invocation.getter(#removeWatchlist),
        returnValue: _FakeRemoveWatchlistMovie_4(
          this,
          Invocation.getter(#removeWatchlist),
        ),
      ) as _i6.RemoveWatchlistMovie);
  @override
  _i7.MovieDetail get itemDetail => (super.noSuchMethod(
        Invocation.getter(#itemDetail),
        returnValue: _FakeMovieDetail_5(
          this,
          Invocation.getter(#itemDetail),
        ),
      ) as _i7.MovieDetail);
  @override
  _i15.RequestState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i15.RequestState.Empty,
      ) as _i15.RequestState);
  @override
  List<_i16.Movie> get recommendations => (super.noSuchMethod(
        Invocation.getter(#recommendations),
        returnValue: <_i16.Movie>[],
      ) as List<_i16.Movie>);
  @override
  _i15.RequestState get recommendationState => (super.noSuchMethod(
        Invocation.getter(#recommendationState),
        returnValue: _i15.RequestState.Empty,
      ) as _i15.RequestState);
  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: '',
      ) as String);
  @override
  String get recommendationMessage => (super.noSuchMethod(
        Invocation.getter(#recommendationMessage),
        returnValue: '',
      ) as String);
  @override
  bool get isAddedToWatchlist => (super.noSuchMethod(
        Invocation.getter(#isAddedToWatchlist),
        returnValue: false,
      ) as bool);
  @override
  String get watchlistMessage => (super.noSuchMethod(
        Invocation.getter(#watchlistMessage),
        returnValue: '',
      ) as String);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i17.Future<void> fetchMovieDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchMovieDetail,
          [id],
        ),
        returnValue: _i17.Future<void>.value(),
        returnValueForMissingStub: _i17.Future<void>.value(),
      ) as _i17.Future<void>);
  @override
  _i17.Future<void> addWatchlistMovies(_i7.MovieDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWatchlistMovies,
          [movie],
        ),
        returnValue: _i17.Future<void>.value(),
        returnValueForMissingStub: _i17.Future<void>.value(),
      ) as _i17.Future<void>);
  @override
  _i17.Future<void> removeFromWatchlistMovies(_i7.MovieDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlistMovies,
          [movie],
        ),
        returnValue: _i17.Future<void>.value(),
        returnValueForMissingStub: _i17.Future<void>.value(),
      ) as _i17.Future<void>);
  @override
  _i17.Future<void> fetchMovieOrTvSeriesDetail({
    required _i17.Future<_i18.Either<_i19.Failure, _i7.MovieDetail>>?
        detailResult,
    required _i17.Future<_i18.Either<_i19.Failure, List<_i16.Movie>>>?
        recommendationResult,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMovieOrTvSeriesDetail,
          [],
          {
            #detailResult: detailResult,
            #recommendationResult: recommendationResult,
          },
        ),
        returnValue: _i17.Future<void>.value(),
        returnValueForMissingStub: _i17.Future<void>.value(),
      ) as _i17.Future<void>);
  @override
  _i17.Future<void> addWatchlist({
    required _i17.Future<_i18.Either<_i19.Failure, String>>? saveWatchlist,
    required _i17.Future<void>? loadStatus,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWatchlist,
          [],
          {
            #saveWatchlist: saveWatchlist,
            #loadStatus: loadStatus,
          },
        ),
        returnValue: _i17.Future<void>.value(),
        returnValueForMissingStub: _i17.Future<void>.value(),
      ) as _i17.Future<void>);
  @override
  _i17.Future<void> removeFromWatchlist({
    required _i17.Future<_i18.Either<_i19.Failure, String>>? removeWatchlist,
    required _i17.Future<void>? loadStatus,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlist,
          [],
          {
            #removeWatchlist: removeWatchlist,
            #loadStatus: loadStatus,
          },
        ),
        returnValue: _i17.Future<void>.value(),
        returnValueForMissingStub: _i17.Future<void>.value(),
      ) as _i17.Future<void>);
  @override
  _i17.Future<void> loadWatchlistStatus(
          _i17.Future<bool>? getWatchListStatus) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadWatchlistStatus,
          [getWatchListStatus],
        ),
        returnValue: _i17.Future<void>.value(),
        returnValueForMissingStub: _i17.Future<void>.value(),
      ) as _i17.Future<void>);
  @override
  void addListener(_i20.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i20.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TvSeriesDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesDetailNotifier extends _i1.Mock
    implements _i21.TvSeriesDetailNotifier {
  MockTvSeriesDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.GetTvSeriesDetail get getTvSeriesDetail => (super.noSuchMethod(
        Invocation.getter(#getTvSeriesDetail),
        returnValue: _FakeGetTvSeriesDetail_6(
          this,
          Invocation.getter(#getTvSeriesDetail),
        ),
      ) as _i8.GetTvSeriesDetail);
  @override
  _i9.GetTvSeriesRecommendations get getTvSeriesRecommendations =>
      (super.noSuchMethod(
        Invocation.getter(#getTvSeriesRecommendations),
        returnValue: _FakeGetTvSeriesRecommendations_7(
          this,
          Invocation.getter(#getTvSeriesRecommendations),
        ),
      ) as _i9.GetTvSeriesRecommendations);
  @override
  _i10.GetWatchListTvSeriesStatus get getWatchListStatus => (super.noSuchMethod(
        Invocation.getter(#getWatchListStatus),
        returnValue: _FakeGetWatchListTvSeriesStatus_8(
          this,
          Invocation.getter(#getWatchListStatus),
        ),
      ) as _i10.GetWatchListTvSeriesStatus);
  @override
  _i11.SaveWatchlistTvSeries get saveWatchlist => (super.noSuchMethod(
        Invocation.getter(#saveWatchlist),
        returnValue: _FakeSaveWatchlistTvSeries_9(
          this,
          Invocation.getter(#saveWatchlist),
        ),
      ) as _i11.SaveWatchlistTvSeries);
  @override
  _i12.RemoveWatchlistTvSeries get removeWatchlist => (super.noSuchMethod(
        Invocation.getter(#removeWatchlist),
        returnValue: _FakeRemoveWatchlistTvSeries_10(
          this,
          Invocation.getter(#removeWatchlist),
        ),
      ) as _i12.RemoveWatchlistTvSeries);
  @override
  _i13.TvSeriesDetail get itemDetail => (super.noSuchMethod(
        Invocation.getter(#itemDetail),
        returnValue: _FakeTvSeriesDetail_11(
          this,
          Invocation.getter(#itemDetail),
        ),
      ) as _i13.TvSeriesDetail);
  @override
  _i15.RequestState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i15.RequestState.Empty,
      ) as _i15.RequestState);
  @override
  List<_i22.TvSeries> get recommendations => (super.noSuchMethod(
        Invocation.getter(#recommendations),
        returnValue: <_i22.TvSeries>[],
      ) as List<_i22.TvSeries>);
  @override
  _i15.RequestState get recommendationState => (super.noSuchMethod(
        Invocation.getter(#recommendationState),
        returnValue: _i15.RequestState.Empty,
      ) as _i15.RequestState);
  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: '',
      ) as String);
  @override
  String get recommendationMessage => (super.noSuchMethod(
        Invocation.getter(#recommendationMessage),
        returnValue: '',
      ) as String);
  @override
  bool get isAddedToWatchlist => (super.noSuchMethod(
        Invocation.getter(#isAddedToWatchlist),
        returnValue: false,
      ) as bool);
  @override
  String get watchlistMessage => (super.noSuchMethod(
        Invocation.getter(#watchlistMessage),
        returnValue: '',
      ) as String);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i17.Future<void> fetchTvSeriesDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchTvSeriesDetail,
          [id],
        ),
        returnValue: _i17.Future<void>.value(),
        returnValueForMissingStub: _i17.Future<void>.value(),
      ) as _i17.Future<void>);
  @override
  _i17.Future<void> addWatchlistTvSeries(_i13.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWatchlistTvSeries,
          [tvSeries],
        ),
        returnValue: _i17.Future<void>.value(),
        returnValueForMissingStub: _i17.Future<void>.value(),
      ) as _i17.Future<void>);
  @override
  _i17.Future<void> removeFromWatchlistTvSeries(
          _i13.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlistTvSeries,
          [tvSeries],
        ),
        returnValue: _i17.Future<void>.value(),
        returnValueForMissingStub: _i17.Future<void>.value(),
      ) as _i17.Future<void>);
  @override
  _i17.Future<void> fetchMovieOrTvSeriesDetail({
    required _i17.Future<_i18.Either<_i19.Failure, _i13.TvSeriesDetail>>?
        detailResult,
    required _i17.Future<_i18.Either<_i19.Failure, List<_i22.TvSeries>>>?
        recommendationResult,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMovieOrTvSeriesDetail,
          [],
          {
            #detailResult: detailResult,
            #recommendationResult: recommendationResult,
          },
        ),
        returnValue: _i17.Future<void>.value(),
        returnValueForMissingStub: _i17.Future<void>.value(),
      ) as _i17.Future<void>);
  @override
  _i17.Future<void> addWatchlist({
    required _i17.Future<_i18.Either<_i19.Failure, String>>? saveWatchlist,
    required _i17.Future<void>? loadStatus,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWatchlist,
          [],
          {
            #saveWatchlist: saveWatchlist,
            #loadStatus: loadStatus,
          },
        ),
        returnValue: _i17.Future<void>.value(),
        returnValueForMissingStub: _i17.Future<void>.value(),
      ) as _i17.Future<void>);
  @override
  _i17.Future<void> removeFromWatchlist({
    required _i17.Future<_i18.Either<_i19.Failure, String>>? removeWatchlist,
    required _i17.Future<void>? loadStatus,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlist,
          [],
          {
            #removeWatchlist: removeWatchlist,
            #loadStatus: loadStatus,
          },
        ),
        returnValue: _i17.Future<void>.value(),
        returnValueForMissingStub: _i17.Future<void>.value(),
      ) as _i17.Future<void>);
  @override
  _i17.Future<void> loadWatchlistStatus(
          _i17.Future<bool>? getWatchListStatus) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadWatchlistStatus,
          [getWatchListStatus],
        ),
        returnValue: _i17.Future<void>.value(),
        returnValueForMissingStub: _i17.Future<void>.value(),
      ) as _i17.Future<void>);
  @override
  void addListener(_i20.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i20.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
