// Mocks generated by Mockito 5.4.4 from annotations
// in ditonton/test/presentation/pages/home_list_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i11;

import 'package:dartz/dartz.dart' as _i9;
import 'package:ditonton/common/failure.dart' as _i10;
import 'package:ditonton/common/state_enum.dart' as _i6;
import 'package:ditonton/domain/entities/movie.dart' as _i5;
import 'package:ditonton/domain/entities/tv_series.dart' as _i13;
import 'package:ditonton/domain/usecases/get_now_playing_movies.dart' as _i2;
import 'package:ditonton/domain/usecases/get_on_air_tv_series.dart' as _i3;
import 'package:ditonton/presentation/provider/home_movie_list_notifier.dart'
    as _i4;
import 'package:ditonton/presentation/provider/home_tv_series_list_notifier.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetNowPlayingMovies_0 extends _i1.SmartFake
    implements _i2.GetNowPlayingMovies {
  _FakeGetNowPlayingMovies_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetOnAirTvSeries_1 extends _i1.SmartFake
    implements _i3.GetOnAirTvSeries {
  _FakeGetOnAirTvSeries_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeMovieListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeMovieListNotifier extends _i1.Mock
    implements _i4.HomeMovieListNotifier {
  MockHomeMovieListNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetNowPlayingMovies get getNowPlayingMovies => (super.noSuchMethod(
        Invocation.getter(#getNowPlayingMovies),
        returnValue: _FakeGetNowPlayingMovies_0(
          this,
          Invocation.getter(#getNowPlayingMovies),
        ),
      ) as _i2.GetNowPlayingMovies);

  @override
  List<_i5.Movie> get homeList => (super.noSuchMethod(
        Invocation.getter(#homeList),
        returnValue: <_i5.Movie>[],
      ) as List<_i5.Movie>);

  @override
  _i6.RequestState get homelistState => (super.noSuchMethod(
        Invocation.getter(#homelistState),
        returnValue: _i6.RequestState.Empty,
      ) as _i6.RequestState);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> fetchNowPlayingList() => (super.noSuchMethod(
        Invocation.method(
          #fetchNowPlayingList,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> getCurrenlyOnAirOrNowPlaying(
          _i8.Future<_i9.Either<_i10.Failure, List<_i5.Movie>>>? execute) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrenlyOnAirOrNowPlaying,
          [execute],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [HomeTvSeriesListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeTvSeriesListNotifier extends _i1.Mock
    implements _i12.HomeTvSeriesListNotifier {
  MockHomeTvSeriesListNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetOnAirTvSeries get getOnAirTvSeries => (super.noSuchMethod(
        Invocation.getter(#getOnAirTvSeries),
        returnValue: _FakeGetOnAirTvSeries_1(
          this,
          Invocation.getter(#getOnAirTvSeries),
        ),
      ) as _i3.GetOnAirTvSeries);

  @override
  List<_i13.TvSeries> get homeList => (super.noSuchMethod(
        Invocation.getter(#homeList),
        returnValue: <_i13.TvSeries>[],
      ) as List<_i13.TvSeries>);

  @override
  _i6.RequestState get homelistState => (super.noSuchMethod(
        Invocation.getter(#homelistState),
        returnValue: _i6.RequestState.Empty,
      ) as _i6.RequestState);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> fetchOnAirTvSeries() => (super.noSuchMethod(
        Invocation.method(
          #fetchOnAirTvSeries,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> getCurrenlyOnAirOrNowPlaying(
          _i8.Future<_i9.Either<_i10.Failure, List<_i13.TvSeries>>>? execute) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrenlyOnAirOrNowPlaying,
          [execute],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
