// Mocks generated by Mockito 5.0.16 from annotations
// in tv/test/presentation/pages/watchlist_tvs_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutter_bloc/flutter_bloc.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv/domain/usecases/watchlist/get_watchlist_tvs.dart' as _i2;
import 'package:tv/tv.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetWatchlistTvs_0 extends _i1.Fake implements _i2.GetWatchlistTvs {}

class _FakeTvWatchlistState_1 extends _i1.Fake implements _i3.TvWatchlistState {
}

/// A class which mocks [TvWatchlistCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvWatchlistCubit extends _i1.Mock implements _i3.TvWatchlistCubit {
  MockTvWatchlistCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetWatchlistTvs get getWatchlistTvs =>
      (super.noSuchMethod(Invocation.getter(#getWatchlistTvs),
          returnValue: _FakeGetWatchlistTvs_0()) as _i2.GetWatchlistTvs);
  @override
  _i3.TvWatchlistState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeTvWatchlistState_1()) as _i3.TvWatchlistState);
  @override
  _i4.Stream<_i3.TvWatchlistState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i3.TvWatchlistState>.empty())
          as _i4.Stream<_i3.TvWatchlistState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  _i4.Future<void> fetchWatchlistTvs() =>
      (super.noSuchMethod(Invocation.method(#fetchWatchlistTvs, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  void emit(_i3.TvWatchlistState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onChange(_i5.Change<_i3.TvWatchlistState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  _i4.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  String toString() => super.toString();
}
