// Mocks generated by Mockito 5.0.16 from annotations
// in tv/test/presentation/cubit/season_detail/tv_season_detail_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:core/core.dart' as _i6;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv/domain/entities/season_detail.dart' as _i7;
import 'package:tv/domain/repositories/tv_repository.dart' as _i2;
import 'package:tv/domain/usecases/get_tv_season_detail.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeTvRepository_0 extends _i1.Fake implements _i2.TvRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetTvSeasonDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvSeasonDetail extends _i1.Mock implements _i4.GetTvSeasonDetail {
  MockGetTvSeasonDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvRepository_0()) as _i2.TvRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.SeasonDetail>> execute(
          int? id, int? seasonNumber) =>
      (super.noSuchMethod(Invocation.method(#execute, [id, seasonNumber]),
          returnValue: Future<_i3.Either<_i6.Failure, _i7.SeasonDetail>>.value(
              _FakeEither_1<_i6.Failure, _i7.SeasonDetail>())) as _i5
          .Future<_i3.Either<_i6.Failure, _i7.SeasonDetail>>);
  @override
  String toString() => super.toString();
}
